name: pruebadepablo
favicon: null
layout_spectrum: 0.73898
typography_spectrum: 0.94061
title: pruebisima
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#89934c'
    - '#373a4d'
    - '#f5ac79'
    - '#fefefc'
    - '#010000'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
